apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-persistent-volume-claim
  namespace: des
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
