apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config-map
  namespace: des
data:
  RAILS_ENV: 'production'
  ROOT_DOMAIN: 'dreams.test' # assuming /etc/hosts mapping to cluster
  ACTIVE_STORAGE_SERVICE: 'local'
  ACTIVE_STORAGE_CUSTOMER_UPLOADED_IMAGES_SERVICE: 'local'
  FORCE_SSL: 'false'
  # Default values for RAILS_ENV production, uncomment to override:
  # PORT: 3000
  # RAILS_MAX_THREADS: 5
  # LOG_LEVEL: info
  # CDN_HOST: (request host)
