apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-deployment
  namespace: des
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
        - name: web-server
          image: des:latest
          imagePullPolicy: Never
          command:
            - ./docker/self-hosted/run-web-server.sh
          envFrom:
            - configMapRef:
                name: common-config-map
            - secretRef:
                name: common-secret
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            limits:
              cpu: 1024m
              memory: 1024Mi
            requests:
              cpu: 512m
              memory: 512Mi
          volumeMounts:
            - mountPath: /app/storage
              name: storage-volume
      volumes:
        - name: storage-volume
          persistentVolumeClaim:
            claimName: storage-persistent-volume-claim
