apiVersion: v1
kind: PersistentVolume
metadata:
  name: des-db-persistent-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    # This is assuming a minikube cluster, see:
    # https://minikube.sigs.k8s.io/docs/handbook/persistent_volumes/
    path: /data/des-db-persistent-volume
