apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-persistent-volume-claim
  namespace: des
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
